---

- name: Deploy kube-metrics-server on cluster
  local_action:
    module: k8s
    state: "{{ kube_metrics_server_resource_state }}"
    kubeconfig: "{{ kube_metrics_server_kubeconfig }}"
    definition: "{{ lookup('template', item) }}"
  with_items:
    - aggregated-metrics-reader.yml.j2
    - auth-delegator.yml.j2
    - auth-reader.yml.j2
    - metrics-apiservice.yml.j2
    - metrics-server-secret.yml.j2
    - metrics-server-deployment.yml.j2
    - metrics-server-service.yml.j2
    - resource-reader.yml.j2
